version: 2.1

_xvfb: &xvfb
  name: Start Xvfb virtual framebuffer
  command: |
    echo "export DISPLAY=:99" >> $BASH_ENV
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset -nolisten tcp -nolisten unix

jobs:
    build_docs:
      docker:
        - image: circleci/python:3.8.5-buster
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              set -e
              echo "set -e" >> $BASH_ENV
              echo "export XDG_RUNTIME_DIR=/tmp/runtime-circleci" >> $BASH_ENV
              echo "export MNE_3D_BACKEND=pyvista" >> $BASH_ENV
              echo "export PYTHONUNBUFFERED=1" >> $BASH_ENV
              echo "BASH_ENV:"
              cat $BASH_ENV
        - run:
            <<: *xvfb
        - run:
            name: Install OpenGL
            command: |
              sudo apt-get update --allow-releaseinfo-change
              sudo apt-get install -y git libopenmpi-dev openmpi-bin
              sudo apt-get install libosmesa6 libglx-mesa0 libopengl0 libglx0 libdbus-1-3 \
                libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
                libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libxcb-xinerama0
              sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb-util.so.0 /usr/lib/x86_64-linux-gnu/libxcb-util.so.1
        - run:
            name: Install dependencies
            command: |
              python -m pip install --progress-bar off --upgrade pip setuptools wheel
              python -m pip install --progress-bar off -r doc/doc-requirements.txt
              python -m pip install --progress-bar off --upgrade pytest coverage
              python -m pip install -e .
              echo "localhost slots=50">hostfile
        - run:
            name: Check PyQt5
            command: LD_DEBUG=libs python -c "from PyQt5.QtWidgets import QApplication, QWidget; app = QApplication([])"
        - run:
            name: Check installation
            command: |
               which python
               QT_DEBUG_PLUGINS=1 mne sys_info
               python -c "import numpy; numpy.show_config()"
               LIBGL_DEBUG=verbose python -c "import pyvistaqt; pyvistaqt.BackgroundPlotter(show=True)"
        - run:
            name: run test
            no_output_timeout: 30m
            command: |
              coverage run -m pytest;
              coverage report;
              coverage html;
        - run:
            name: make html
            no_output_timeout: 30m
            command: |
              cd doc;
              export OMP_NUM_THREADS=1;
              make html;
        - store_artifacts:
            path: doc/_build/html/
            destination: dev

workflows:
  version: 2

  default:
    jobs:
      - build_docs
